hooks:
  update_modules:
    pre:
      - echo "before update-modules"
    post:
      - echo "after update-modules"
  release:
    pre:
      - echo "before release"
    post:
      - echo "after release"
  gh_pages:
    pre:
      - echo "before gh-pages"
    post:
      - echo "after gh-pages"
config:
  git_user_name: CircleCI
  git_user_email: circleci@example.com
  npm_update_depth: 0
  version_prefix: v
  create_branch: false
  npm_shrinkwrap: false
  create_gh_pages: false
  gh_pages_dir: null
circle: {}
